
version "4.15.1"

#include "zscript/wf_handler.zs"
#include "zscript/wf_handler_static.zs"
#include "zscript/wf_tex_swap.zs"
#include "zscript/wf_tex_swap_all.zs"
#include "zscript/wf_mus_swap.zs"
#include "zscript/wf_mus_sigil.zs"
#include "zscript/wf_mus_idkfa.zs"
#include "zscript/wf_sbar.zs"
#include "zscript/wf_sbar_alt.zs"
#include "zscript/wf_newgame.zs"
#include "zscript/wf_story.zs"
#include "zscript/wf_map_fixes.zs"
#include "zscript/wf_defaults.zs"
