name: Bug report
description: File a bug report
title: "[Bug] "
labels: ["bug"]
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
      - label: I have searched the existing issues
        required: true
  - type: input
    attributes:
      label: WadFusion Version
      description: |
        Which version of WadFusion are you using? Write down the git commit SHA if you're using a dev build.
        
        I would greatly appreciate it if you first check if the issue also exists in the latest dev build.
      placeholder: e.g. 1.5.1 or c8a5286
    validations:
      required: false
  - type: input
    attributes:
      label: Operating System
      description: Which operating system are you using?
      placeholder: i.e. GNU/Linux distro, Windows version, etc.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Bug Description
      description: A concise description of what you're experiencing.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. 
        2. 
        3. 
        4. 
    validations:
      required: false
  - type: textarea
    attributes:
      label: Attachments
      placeholder: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
